services:
  # Mysql
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=buuking-root-password
      - MYSQL_DATABASE=buuking-dot-com
      - MYSQL_USER=buuking
      - MYSQL_PASSWORD=gnikuub
    ports:
      - "3306:3306"
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysql -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} -D$${MYSQL_DATABASE} -e 'SELECT 1;'"
      ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  # Metrics
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  # Logs
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  #Tracing
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - ./tmp/tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    environment:
      - OTEL_EXPORTER_OTLP_CORS_ALLOWED_ORIGINS=localhost:4200

  # UI for Metrics, Logs and Tracing
  grafana:
    image: grafana/grafana:10.2.2
    volumes:
      - ./config/grafana/dashboards/observability-dashboard.json:/var/lib/grafana/dashboards/observability-dashboard.json
      - ./config/grafana/provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml

    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"

  buuking-dot-com:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    image: buuking:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=buuking-dot-com
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/buuking-dot-com
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  prom_data:
