services:
  # Mysql
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=buuking-root-password
      - MYSQL_DATABASE=buuking-dot-com
      - MYSQL_USER=buuking
      - MYSQL_PASSWORD=gnikuub
    ports:
      - "3306:3306"
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysql -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} -D$${MYSQL_DATABASE} -e 'SELECT 1;'"
      ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55