{
 "title": "Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total of Reservations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "reservation_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reservations not Paid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "reservation_not_paid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total of Searchs for Available Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "search_for_available_rooms_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservation not Acknowledged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "reservation_not_acknowledged", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reservation Exchange on Hold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "reservation_exchange_on_hold", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Declined Reservation on Hold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "declined_reservation_on_hold_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted Reservation on Hold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "accepted_reservation_on_hold_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}